### ISSUE TITLE
Support systemd as the underlying init system

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/runit#79]
We need to start runsvdir under systemd like we do for sysv and upstart. It's probably worth separating each underlying init system out to its own recipe, and use the ohai-detected automatic attribute `init_package` to select the right thing.

**Comment by kbaltrinic** [comment]
+1 on this.  Any idea when this will get into a releas?  Looks like we have gone from 1.5 to 1.7 w/o this being resolved yet.

**Comment by jtimberman** [comment]
I don't have any idea on when this work would be done. I personally don't have cycles to work on this cookbook currently.

**Comment by mfischer-zd** [comment]
> We need to start runsvdir under systemd

Why not use native systemd units?

**Comment by jtimberman** [comment]
What do you mean, @mfischer-zd? Instead of using runit entirely, use systemd units? That would rather defeat the purpose of this cookbook; there are a lot of runit-managed services out there. Much of the infrastructure and applications that Chef Software runs, for example, use runit.

**Comment by mfischer-zd** [comment]
I'm (in a roundabount way) offering constructive advice to would-be users of this cookbook.  If you're on a systemd-based system, my opinion and experience is that there's not really a need for this cookbook, and that you're better off converting your runit services to systemd units.

This includes Chef Software's own services.

**Comment by tas50** [comment]
@mfischer-zd Runit is pretty heavily entrenched in Chef cookbooks since most of the cookbooks were developed around 2008/2009 when the state of distro init systems was fairly sad. The need for an init system that started back up when the service failed or could auto restart at high memory conditions was huge, yet sys-v was...sys-v.  Fast forward nearly a decade and we have Upstart and Systemd on every current released distro and most of the currently supported distros. In general as I rework cookbooks I'm removing support for Runit. It adds additional packages and complexity, and requires admins to understand yet another technology. So far tomcat, memcached, push-jobs, and nginx have been de-runit'd. This cookbooks will live on for everyone still using runit on their own products and for the Ched products where runit ships as part of an omnibus package, but I suspect its use will dwindle over time and that's just fine by me. I'm going to close this out since I don't see it as something we'll ever tackle or something that's particularly necessary at this point in runits lifecycle.
